import type { Metadata } from "next";
import "./globals.css"

export const metadata: Metadata = {
  title: "My first React App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="se">
      <body>
        {children}
      </body>
    </html>
  );
}
