import type { Metadata } from "next";
import "./globals.css"
import Navbar from "@/components/navbar";

export const metadata: Metadata = {
  title: "My first React App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header className="bg-emerald-800 text-primary-foreground p-3">
          <Navbar />
        </header>
        <main className="p-3">
          {children}
        </main>
      </body>
    </html>
  );
}
